AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  IndexTweets:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: IndexTweets.handler
      Runtime: python2.7
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 300
      Role: 'arn:aws:iam::684197843106:role/lambda-s3-execution-role'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
  Bucket1:
    Type: 'AWS::S3::Bucket'
